GET localhost:8080/messages
Content-Type: application/json
Origin: http://localhost:3000

###

PATCH localhost:8080/message/1
Content-Type: application/json
Origin: http://localhost:3000

{
    "message": "Hello World"
}
